language: python
python:
  - "3.6"

env:
  - DJANGO_ENV=Testing

addons:
  postgresql: "9.4"

before_script:
  - pip install -r requirements.txt
  - pip install coveralls
  - psql -c 'create database authors;' -U postgres
  - python manage.py makemigrations  reporter --noinput
  - python manage.py makemigrations  password_reset_token --noinput
  - python manage.py makemigrations --noinput
  - python manage.py migrate --noinput

script:
  - pytest -v --cov=authors --cov-report=term-missing

after_success:
  - coveralls
